<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="row small-uncollapse">
    <div class="small-12 medium-8 columns">
        <? $this->load->view('include/pagetitle'); ?>
        <br/>
        <ul class="green-bullet text-justify">
            <li><span class="hammer-word">La passion</span> : nos enseignants qui sont <strong>captiv&eacute;s</strong> par les sciences et l&rsquo;enseignement sauront <strong>transmettre</strong> aux &eacute;l&egrave;ves l&rsquo;envie d&rsquo;<strong>apprendre</strong> et de se <strong>d&eacute;passer</strong>. Cette passion qui anime nos enseignants aidera &agrave; cr&eacute;er un sentiment de <strong>proximit&eacute;</strong> chez vos enfants. Une proximit&eacute; indispensable pour <strong>tirer un &eacute;l&egrave;ve vers le haut</strong>.</li>
            <li><span class="hammer-word">La p&eacute;dagogie</span> : nous avons l&rsquo;exigence de vous proposer un enseignant hautement <strong>dipl&ocirc;m&eacute;</strong> et <strong>p&eacute;dagogue</strong>. Chaque profil d&rsquo;enseignant d&eacute;sireux d&rsquo;int&eacute;grer notre &eacute;quipe p&eacute;dagogique est <strong>scrupuleusement</strong> analys&eacute; en mettant un point d&rsquo;orgue &agrave; sa mani&egrave;re de <strong>transmettre ses connaissances</strong>.</li>
            <li><span class="hammer-word">Qualit&eacute;</span> : apr&egrave;s une <strong>pr&eacute;-s&eacute;lection</strong> sur C.V., le <strong>niveau scientifique</strong> ainsi que la <strong>p&eacute;dagogie</strong> de chaque candidat sont <strong>m&eacute;ticuleusement v&eacute;rifi&eacute;s</strong> apr&egrave;s une mise en situation concr&egrave;te ainsi qu&rsquo;un <strong>entretien individuel</strong>. GoSciences exige un <strong>extrait de casier judiciaire vierge</strong> avant de confier un &eacute;l&egrave;ve &agrave; un de ses futurs enseignants. Par ailleurs, un <strong>suivi p&eacute;dagogique</strong> vous sera adress&eacute; chaque mois.</li>
            <li><span class="hammer-word">Adaptabilit&eacute;</span> : chaque &eacute;l&egrave;ve est <strong>diff&eacute;rent</strong> et chaque &eacute;l&egrave;ve &agrave; ses <strong>propres difficult&eacute;s</strong>. Nos enseignants mettront en place un programme <strong>adapt&eacute;</strong> pour chaque &eacute;l&egrave;ve apr&egrave;s <strong>&eacute;valuation</strong> de ses points forts et de ses points faibles lors du premier cours. Le suivi p&eacute;dagogique mensuel permettra de faire le point sur les <strong>techniques d&rsquo;enseignement</strong> employ&eacute;es et ainsi, les conforter ou les corriger.</li>
            <li><span class="hammer-word">Accessibilit&eacute;</span> : nous d&eacute;sirons d&eacute;velopper des <strong>relations durables</strong> et cr&eacute;er un <strong>lien de</strong> <strong>confiance</strong> avec nos &eacute;l&egrave;ves et leurs familles. Nous nous engageons &agrave; rester &agrave; votre enti&egrave;re disposition la <strong>semaine et le week-end</strong> afin de r&eacute;pondre &agrave; <strong>vos attentes</strong> dans les plus brefs d&eacute;lais.</li>
        </ul>
        
    </div>
    <? $this->load->view('include/sidebar'); ?>

</div>